export type Lang = "tr" | "en";

export const content = {
  tr: {
    nav: {
      home: "ANASAYFA",
      tasfiye: "TASFİYE",
      murekkep: "MÜREKKEP VE KÖZ",
      author: "YAZAR",
      contact: "İLETİŞİM",
    },
    home: {
      kicker: "BERKAYDOGAN.CO — 2026",
      heroSub: ["Yıkmak, kurmanın tek yoludur.", "161 sayfalık bir varoluş infazına", "hoş geldiniz."],
      ctaBook: "KİTABI GÖR →",
      ctaAuthor: "YAZAR →",
      heroPanelTop: "DENEME KİTABI",
      heroPanelBottom: "ARALIK 2026",
      manifestoKicker: "MANİFESTO — 2026",
      manifestoQuote: "\"Gerçek, yağlarından arındığında ortaya çıkan kemiktir.\"",
      manifestoAuthor: "— BERKAY DOĞAN, TASFİYE MANİFESTOSU",
      books: {
        tasfiyeKicker: "ARALIK 2026 — DENEME",
        tasfiyeTitle: "TASFİYE",
        tasfiyeDesc: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir.",
        tasfiyeLink: "DAHA FAZLA →",
        murekkepKicker: "ARALIK 2025 — ŞİİR",
        murekkepTitle: "MÜREKKEP\nVE KÖZ",
        murekkepDesc: "Bir Şairin Hesabı. İskenderiye Yayınları. Trendyol Şiir #1.",
        murekkepLink: "DAHA FAZLA →",
      },
      bioKicker: "YAZAR",
      bioText: "Berkay Doğan, İstanbul'da yaşayan şair ve yazardır. Mürekkep ve Köz (2025) ve Tasfiye (2026) kitaplarının yazarıdır.",
      bioLink: "BİYOGRAFİ →",
    },
    tasfiye: {
      kicker: "BERKAY DOĞAN — DENEME — ARALIK 2026",
      title: "TASFİYE",
      heroDesc: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir.",
      meta: [
        { label: "YIL", value: "2026" },
        { label: "TÜR", value: "DENEME" },
        { label: "SAYFA", value: "161" },
        { label: "DURUM", value: "YAKINLAŞIYOR" },
      ],
      aboutKicker: "KİTAP HAKKINDA",
      aboutText: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir. Deneme kitabı. Aralık 2026.",
      contentsKicker: "İÇİNDEKİLER",
      bolumler: [
        { no: "I", baslik: "Modern Dünyanın Enkazı", alt: "Toplumsal Eleştiri", count: "16 METİN" },
        { no: "II", baslik: "Toplumsal Klinik", alt: "İnsanın İfşası", count: "2 METİN" },
        { no: "III", baslik: "Büyük Tasfiye", alt: "Arınma", count: "8 METİN" },
      ],
      ctaKicker: "ÇIKIŞ TARİHİ: ARALIK 2026",
      ctaTitle: "Perde açılıyor.",
    },
    murekkep: {
      kicker: "BERKAY DOĞAN — ŞİİR — ARALIK 2025",
      title: "MÜREKKEP VE KÖZ",
      subtitle: "Bir Şairin Hesabı",
      heroDesc: "2017–2022 yılları arasında, boğucu bir yalnızlığın, ulusal kaosun ve varoluşsal krizlerin içinden sökülerek yazılan dizeler.",
      meta: [
        { label: "YIL", value: "2025" },
        { label: "TÜR", value: "ŞİİR" },
        { label: "YAYINEVİ", value: "İSKENDERİYE" },
        { label: "TRENDYOL", value: "#1" },
      ],
      aboutKicker: "KİTAP HAKKINDA",
      aboutText: "Çıkışından altı ay sonra edebiyatın dev çınarlarını geride bırakarak Türkiye'nin en büyük pazar yerinde Şiir Kategorisi \"En Çok Ziyaret Edilenler\" listesinde 1. sıraya yerleşti. Bu, bağımsız ve ham emeğin mutlak zaferidir.",
      buyKicker: "NEREDEN ALINIR",
      buyLinks: [
        { name: "Trendyol", url: "https://www.trendyol.com" },
        { name: "Kitapyurdu", url: "https://www.kitapyurdu.com" },
        { name: "BKM Kitap", url: "https://www.bkmkitap.com" },
        { name: "İstanbul Kitapçısı", url: "#" },
        { name: "Amazon", url: "https://www.amazon.com" },
      ],
      reviewKicker: "OKURLARDAN",
      review: "\"Harika bir kitap, şimdiye kadar okuduğum şiir kitaplarından çok farklı, okumak isteyenlere tavsiye ederim.\"",
      reviewSource: "TRENDYOL",
    },
    author: {
      kicker: "YAZAR — BİYOGRAFİ",
      title: "BERKAY\nDOĞAN",
      aboutKicker: "HAKKINDA",
      bio: [
        "Berkay Doğan, İstanbul'da yaşayan Türk şair ve yazardır. Şiirleri Valsanat Dergisi'nde yayımlanmış; okur platformlarında yüksek puanlar almıştır.",
        "İlk şiir kitabı Mürekkep ve Köz: Bir Şairin Hesabı Aralık 2025'te İskenderiye Yayınları'ndan çıktı. İkinci kitabı Tasfiye, bir deneme kitabı olarak Aralık 2026'da yayımlanacak.",
      ],
      worksKicker: "ESERLER",
      works: [
        { yil: "2025", eser: "Mürekkep ve Köz: Bir Şairin Hesabı", tur: "ŞİİR", yayin: "İskenderiye Yayınları" },
        { yil: "2026", eser: "Tasfiye", tur: "DENEME", yayin: "Yakında" },
      ],
    },
    contact: {
      kicker: "İLETİŞİM",
      title: ["YAZI,", "GERÇEKTEN"],
      desc: "Havadan sudan konuşmak için değil, gerçekten kanayan bir yaran varsa yaz.",
      emailLabel: "E-POSTA",
      instaLabel: "INSTAGRAM",
    },
    footer: {
      sign: "Bütün yalanlar düzenin, kelimeler Berkay Doğan'ındır.",
    },
  },
  en: {
    nav: {
      home: "HOME",
      tasfiye: "TASFİYE",
      murekkep: "INK AND EMBER",
      author: "AUTHOR",
      contact: "CONTACT",
    },
    home: {
      kicker: "BERKAYDOGAN.CO — 2026",
      heroSub: ["To destroy is the only way to build.", "Welcome to a 161-page", "execution of existence."],
      ctaBook: "VIEW THE BOOK →",
      ctaAuthor: "AUTHOR →",
      heroPanelTop: "ESSAY COLLECTION",
      heroPanelBottom: "DECEMBER 2026",
      manifestoKicker: "MANIFESTO — 2026",
      manifestoQuote: "\"Truth is the bone that remains once the fat is stripped away.\"",
      manifestoAuthor: "— BERKAY DOĞAN, TASFİYE MANIFESTO",
      books: {
        tasfiyeKicker: "DECEMBER 2026 — ESSAY",
        tasfiyeTitle: "TASFİYE",
        tasfiyeDesc: "Tasfiye is a name given to everything we choose not to see.",
        tasfiyeLink: "MORE →",
        murekkepKicker: "DECEMBER 2025 — POETRY",
        murekkepTitle: "INK AND\nEMBER",
        murekkepDesc: "A Poet's Reckoning. İskenderiye Publishing. #1 in Poetry on Trendyol.",
        murekkepLink: "MORE →",
      },
      bioKicker: "AUTHOR",
      bioText: "Berkay Doğan is a poet and writer based in Istanbul. He is the author of Ink and Ember (2025) and Tasfiye (2026).",
      bioLink: "BIOGRAPHY →",
    },
    tasfiye: {
      kicker: "BERKAY DOĞAN — ESSAY — DECEMBER 2026",
      title: "TASFİYE",
      heroDesc: "Tasfiye is a name given to everything we choose not to see.",
      meta: [
        { label: "YEAR", value: "2026" },
        { label: "GENRE", value: "ESSAY" },
        { label: "PAGES", value: "161" },
        { label: "STATUS", value: "APPROACHING" },
      ],
      aboutKicker: "ABOUT THE BOOK",
      aboutText: "Tasfiye is a name given to everything we choose not to see. An essay collection. December 2026.",
      contentsKicker: "CONTENTS",
      bolumler: [
        { no: "I", baslik: "The Wreckage of the Modern World", alt: "Social Critique", count: "16 TEXTS" },
        { no: "II", baslik: "The Social Clinic", alt: "The Exposure of Man", count: "2 TEXTS" },
        { no: "III", baslik: "The Great Purge", alt: "Purification", count: "8 TEXTS" },
      ],
      ctaKicker: "RELEASE DATE: DECEMBER 2026",
      ctaTitle: "The curtain rises.",
    },
    murekkep: {
      kicker: "BERKAY DOĞAN — POETRY — DECEMBER 2025",
      title: "INK AND EMBER",
      subtitle: "A Poet's Reckoning",
      heroDesc: "Verses torn out from within a suffocating solitude, national chaos, and existential crises between 2017 and 2022.",
      meta: [
        { label: "YEAR", value: "2025" },
        { label: "GENRE", value: "POETRY" },
        { label: "PUBLISHER", value: "İSKENDERİYE" },
        { label: "TRENDYOL", value: "#1" },
      ],
      aboutKicker: "ABOUT THE BOOK",
      aboutText: "Six months after its release, it surpassed the giants of literature to claim the #1 spot in the \"Most Visited\" Poetry category on Turkey's largest marketplace. This is the absolute triumph of independent, raw craft.",
      buyKicker: "WHERE TO BUY",
      buyLinks: [
        { name: "Trendyol", url: "https://www.trendyol.com" },
        { name: "Kitapyurdu", url: "https://www.kitapyurdu.com" },
        { name: "BKM Kitap", url: "https://www.bkmkitap.com" },
        { name: "İstanbul Kitapçısı", url: "#" },
        { name: "Amazon", url: "https://www.amazon.com" },
      ],
      reviewKicker: "FROM READERS",
      review: "\"A wonderful book, very different from any poetry I've read before. I recommend it to anyone who wants to read.\"",
      reviewSource: "TRENDYOL",
    },
    author: {
      kicker: "AUTHOR — BIOGRAPHY",
      title: "BERKAY\nDOĞAN",
      aboutKicker: "ABOUT",
      bio: [
        "Berkay Doğan is a Turkish poet and writer based in Istanbul. His poems have been published in Valsanat Magazine and have received high ratings on reader platforms.",
        "His first poetry collection, Ink and Ember: A Poet's Reckoning, was published by İskenderiye Publishing in December 2025. His second book, Tasfiye, will be published as an essay collection in December 2026.",
      ],
      worksKicker: "WORKS",
      works: [
        { yil: "2025", eser: "Ink and Ember: A Poet's Reckoning", tur: "POETRY", yayin: "İskenderiye Publishing" },
        { yil: "2026", eser: "Tasfiye", tur: "ESSAY", yayin: "Forthcoming" },
      ],
    },
    contact: {
      kicker: "CONTACT",
      title: ["WRITE,", "FOR REAL"],
      desc: "Not to make small talk, but if you have a wound that truly bleeds, write.",
      emailLabel: "EMAIL",
      instaLabel: "INSTAGRAM",
    },
    footer: {
      sign: "All lies belong to the order, the words belong to Berkay Doğan.",
    },
  },
} as const;

export function getContent(lang: Lang) {
  return content[lang];
}
