export type Lang = "tr" | "en";

// Mürekkep ve Köz — Trendyol satın alma sayfası (satışta olan kitap)
export const TRENDYOL_URL =
  "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167";

export const content = {
  tr: {
    nav: {
      home: "ANASAYFA",
      kitaplar: "KİTAPLAR",
      tasfiye: "TASFİYE",
      murekkep: "MÜREKKEP VE KÖZ",
      yazilar: "YAZILAR",
      medya: "MEDYA",
      anlar: "ANLAR",
      basinda: "BASINDA",
      author: "YAZAR",
      contact: "İLETİŞİM",
      buy: "SATIN AL",
    },
    home: {
      kicker: "BERKAYDOGAN.CO — 2026",
      heroSub: ["Yıkmak, kurmanın tek yoludur.", "161 sayfalık bir varoluş infazına", "hoş geldiniz."],
      ctaBook: "KİTABI GÖR →",
      ctaAuthor: "YAZAR →",
      heroPanelTop: "DENEME KİTABI",
      heroPanelBottom: "AĞUSTOS 2026",
      manifestoKicker: "MANİFESTO — 2026",
      manifestoQuote: "\"Gerçek, yağlarından arındığında ortaya çıkan kemiktir.\"",
      manifestoAuthor: "— BERKAY DOĞAN, TASFİYE MANİFESTOSU",
      books: {
        tasfiyeKicker: "AĞUSTOS 2026 — DENEME",
        tasfiyeTitle: "TASFİYE",
        tasfiyeDesc: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir.",
        tasfiyeLink: "DAHA FAZLA →",
        murekkepKicker: "ARALIK 2025 — ŞİİR",
        murekkepTitle: "MÜREKKEP\nVE KÖZ",
        murekkepDesc: "Bir Şairin Hesabı. İskenderiye Yayınları. Trendyol Şiir #1.",
        murekkepLink: "DAHA FAZLA →",
      },
      bioKicker: "YAZAR",
      bioText: "Berkay Doğan, İstanbul'da yaşayan şair ve yazardır. Onun için yazmak bir tercih değil, bir zorunluluktur: yazmak, varoluşun en sessiz itirafıdır.",
      bioLink: "BİYOGRAFİ →",
      heroKickerBrut: "İKİNCİ KİTAP — YAKINDA",
      heroQuoteBrut: "Görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isim.",
      heroCountdownLabels: ["GÜN", "SAAT", "DK"],
      heroDate: "25 AĞUSTOS 2026",
      heroBoxMeta: "Deneme · İskenderiye Yayınları · Ağustos 2026",
      heroBoxLabel: "KAPAK YAKINDA",
      book: {
        eyebrow: "İLK KİTAP · İSKENDERİYE · ARALIK 2025",
        title: "Mürekkep ve Köz",
        subtitle: "Bir Şairin Hesabı",
        desc: "2017–2022 yılları arasında, boğucu bir yalnızlığın, ulusal kaosun ve varoluşsal krizlerin içinden sökülerek yazılan dizeler. 200'den fazla şiir.",
        rating: "Trendyol Şiir · En Çok Ziyaret Edilen #1",
        price: "269 ₺",
        priceTag: "TRENDYOL'DA",
        buyBtn: "Kitabı Satın Al",
        readBtn: "Kitaptan Oku",
        badge: "#1 TRENDYOL ŞİİR",
        hint: "Kapağa tıkla — arkasını çevir",
        hintFlipped: "Ön kapağa dön",
      },
      backCover: {
        kicker: "ARKA KAPAK",
        lead: "Bu kitap, kelimelerin değil; küllerinden yeniden doğmayı seçmiş bir ruhun sesidir.",
        paragraphs: [
          "Sınır tanımayan, aklın zincirlerini kırmış, özgürlüğe kendi bedeniyle meydan okuyan bir sesin… Burada, acı bir yük değil; gerçeğe açılan bir kapı vardır.",
          "Bu dizeler; yalnızlığıyla barışmış, çocukluğunu toprağa gömmüş, sevmenin ve sevilmenin ağırlığı altında şekillenmiş bir ruhun iç hesaplaşmasıdır. Sözler hem bir isyanın hem de bir teslimiyetin izlerini taşır.",
          "Ve sonunda: Yalanlara, sahte yaşanmışlıklara, zincirlere veda eden birinin gürültüsüz ama yenilmez sessizliği kalır geriye. Bu kitap, o sessizliğin yankısıdır.",
        ],
        finalA: "Ben artık sadece kendimim.",
        finalB: "Ve ben yeniden doğdum; şimdi sıra sende.",
      },
      counter: [
        { pre: "Bu ay", num: "312", post: "okur bu sayfayı gördü" },
        { pre: "", num: "146", post: "okur listesinde" },
        { pre: "", num: "#1", post: "Trendyol Şiir · En Çok Ziyaret" },
      ],
      statsKicker: "SAYILAR",
      stats: [
        { num: "200+", label: "ŞİİR" },
        { num: "#1", label: "TRENDYOL ŞİİR" },
        { num: "5/5", label: "OKUR PUANI" },
        { num: "8", label: "SATIŞ KANALI" },
      ],
      pressKicker: "BASINDA",
      press: [
        {
          outlet: "Valsanat Edebiyat Dergisi",
          detail: "51. Sayı · Şubat 2026",
          text: "Ruh-u Katliam şiiri yayınlandı.",
          url: "https://online.fliphtml5.com/jqzww/ezec/#p=1",
        },
        {
          outlet: "Trendyol",
          detail: "Şiir Kategorisi",
          text: "#1 En Çok Ziyaret Edilen.",
          url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167",
        },
        {
          outlet: "Reddit · r/Kitap",
          detail: "Okur değerlendirmesi",
          text: "\"İlk başta eğreti gibi gelen gizemli şiirlerin arasına serpiştirilmiş, hayrete düşüren güzellikte şiirler.\"",
          url: "",
        },
      ],
      colophonKicker: "KÜNYE",
      colophon: [
        { label: "YAYINEVİ", value: "İskenderiye" },
        { label: "YAYIN NO", value: "212" },
        { label: "TÜR", value: "Şiir" },
        { label: "BASIM", value: "Aralık 2025" },
        { label: "ISBN", value: "978-625-9620-32-9" },
        { label: "SAYFA", value: "200+ şiir" },
        { label: "DİL", value: "Türkçe" },
        { label: "YAZAR", value: "Berkay Doğan" },
      ],
      buyGridKicker: "SATIN AL",
      buyGridNote: "Şiir #1",
      ilkKitap: "[ 01 ] İLK KİTAP",
      buyLabel: "SATIN AL →",
      statValue: "#1",
      statLabel: "TRENDYOL ŞİİR\nEN ÇOK SATAN",
      manifestoLead: "Yazmak bir tercih değil.",
      manifestoHl: "Yazmak, varoluşun en sessiz itirafıdır.",
      manifestoSig: "— BERKAY DOĞAN, 2017'DEN BERİ",
      recentKicker: "SON YAZILAR",
      recent: [
        { title: "Bir Yazarın Hesabı", meta: "TASFİYE / 2026", slug: "bir-yazarin-hesabi" },
        { title: "Karanlık Oksijen", meta: "TASFİYE / 2026", slug: "karanlik-oksijen" },
        { title: "Bir Tanrı Değilim", meta: "MÜREKKEP VE KÖZ", slug: "bir-tanri-degilim" },
      ],
    },
    tasfiye: {
      kicker: "BERKAY DOĞAN — DENEME — AĞUSTOS 2026",
      badge: "YAKINDA — AĞUSTOS 2026",
      notifyBtn: "ÇIKINCA HABER VER →",
      notifyUrl: "https://doberkay.substack.com/subscribe",
      launchKicker: "LANSMANA KALAN",
      countdownLabels: ["GÜN", "SAAT", "DK", "SN"],
      launchNote: "Çıktığı an haberin olsun — gürültüsüz, tek bir e-posta.",
      excerptKicker: "KİTAPTAN BİR KESİT",
      excerptText: "Her nefes alışımızda içimize çektiğimiz şeyin salt azot, oksijen ve temiz bir yaşam vaadi olduğunu düşünmek, çağımızın en trajik ve en masum yanılgısıdır.",
      excerptLinkLabel: "Tam kesiti oku →",
      excerptSlug: "karanlik-oksijen",
      title: "TASFİYE",
      heroDesc: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir.",
      meta: [
        { label: "YIL", value: "2026" },
        { label: "TÜR", value: "DENEME" },
        { label: "SAYFA", value: "161" },
        { label: "DURUM", value: "YAKINLAŞIYOR" },
      ],
      aboutKicker: "KİTAP HAKKINDA",
      aboutText: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir. Deneme kitabı. Ağustos 2026.",
      contentsKicker: "İÇİNDEKİLER",
      bolumler: [
        { no: "I", baslik: "Modern Dünyanın Enkazı", alt: "Toplumsal Eleştiri", count: "16 METİN" },
        { no: "II", baslik: "Toplumsal Klinik", alt: "İnsanın İfşası", count: "2 METİN" },
        { no: "III", baslik: "Büyük Tasfiye", alt: "Arınma", count: "8 METİN" },
      ],
      ctaKicker: "ÇIKIŞ TARİHİ: AĞUSTOS 2026",
      ctaTitle: "Perde açılıyor.",
    },
    murekkep: {
      kicker: "BERKAY DOĞAN — ŞİİR — ARALIK 2025",
      title: "MÜREKKEP VE KÖZ",
      subtitle: "Bir Şairin Hesabı",
      heroDesc: "2017–2022 yılları arasında, boğucu bir yalnızlığın, ulusal kaosun ve varoluşsal krizlerin içinden sökülerek yazılan dizeler.",
      meta: [
        { label: "YIL", value: "2025" },
        { label: "TÜR", value: "ŞİİR" },
        { label: "YAYINEVİ", value: "İSKENDERİYE" },
        { label: "TRENDYOL", value: "#1" },
      ],
      aboutKicker: "KİTAP HAKKINDA",
      aboutText: "Çıkışından altı ay sonra edebiyatın dev çınarlarını geride bırakarak Türkiye'nin en büyük pazar yerinde Şiir Kategorisi \"En Çok Ziyaret Edilenler\" listesinde 1. sıraya yerleşti. Bu, bağımsız ve ham emeğin mutlak zaferidir.",
      buyKicker: "NEREDEN ALINIR",
      buyLinks: [
        { name: "Trendyol", url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167" },
        { name: "İskenderiye Kitap", url: "https://www.iskenderiyekitap.com/urun/murekkep-ve-koz-bir-sairin-hesabi-berkay-dogan-9786259620329" },
        { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/murekkep-ve-koz/740626.html" },
        { name: "D&R", url: "https://www.dr.com.tr/kitap/murekkep-ve-koz-bir-sairin-hesabi/berkay-dogan/edebiyat/siir/turk-siiri/urunno=0002206580001" },
        { name: "Hepsiburada", url: "https://www.hepsiburada.com/murekkep-ve-koz-pm-HBC0000BKT7HI" },
        { name: "BKM Kitap", url: "https://www.bkmkitap.com/murekkep-ve-koz" },
        { name: "İstanbul Kitapçısı", url: "https://www.istanbulkitapcisi.com/murekkep-ve-koz" },
        { name: "Maltepe Kitabevi", url: "https://www.maltepekitabevi.com/murekkep-ve-koz" },
      ],
      poemsKicker: "KİTAPTAN",
      poemsIntro: "Mürekkep ve Köz'den birkaç dize.",
      poems: [
        {
          title: "Gri Hayatlar",
          lines: [
            "Akıllarını kaybedenler için üzgünüm, bu dünyada yeterince düşünememek, epeyce aptallığa yol açıyor. İnsanlar renkli hayatlarını kaybederken, gri hayatlarına teslim oluyorlar.",
            "Tabiatımız böyle diyen insanlardan, değişimin kaos getireceğine inanan insanlardan tiksiniyorum.",
            "Keşke siz gri hayatlarınızda boğulsanız da rengimizi kaçırmasanız.",
            "Sizin gri hayatlarınıza lanetler okurken, bu dünyanın rengini griye çevirmenize katlanamazken, yeniden kendi içime dönüyorum.",
          ],
        },
        {
          title: "Geleceğime Âşığım",
          lines: [
            "Hiçbir iyi hatıranın beni bulmadığı yerdeyim.",
            "Çiğneye çiğneye geçiyorum ruhumun daraldığı yerleri.",
            "Geri dönmüyorum, geleceğime âşığım.",
            "Yalan yaşanmışlıklarıma veda ettim.",
            "Denizlerin dalgalarına vurdum.",
            "Yıkılamadım, yıktım.",
            "Kalbim bir gıdım bile kırılmadan devam etti.",
          ],
        },
        {
          title: "Bir Tanrı Değilim",
          lines: [
            "Bazen sevmeyi istersin,",
            "Hayata seni bağlasın istersin.",
            "Umutsuzluk çukurunda zehirli bir kalbi tercih edersin.",
            "Belki bir romantik gül misali olan kalbin,",
            "Medusa'nın lanetine erer.",
            "Nedensiz olmadım böyle.",
            "Ben de severdim eskiden.",
            "Ama istemiyorum artık.",
            "Ben Tanrı değilim.",
            "Herkesi sevemem.",
            "Kimseyi sevemem.",
          ],
        },
      ],
      reviewKicker: "OKURLARDAN",
      reviews: [
        { text: "Harika bir kitap, şimdiye kadar okuduğum şiir kitaplarından çok farklı. Okumak isteyenlere tavsiye ederim.", source: "TRENDYOL" },
        { text: "Bir genç şairden beklenmedik keskinlikte ve şaşırtıcı derecede güzel. Genç bir ruhun ülkemizde nasıl ruh halleri zincirinden geçtiğinin kanıtı.", source: "TRENDYOL" },
        { text: "Kelimelerin köz gibi yavaşça içe işlediği bir şiir yolculuğu. Sade ama güçlü bir anlatım. Uzun zamandır bu kadar dokunan şiirler okumamıştım.", source: "TRENDYOL" },
        { text: "Bu kadar genç bir şairden böyle bir performans çok başarılı. Harika dizeler, muhakkak okunmalı.", source: "TRENDYOL" },
        { text: "İçinden geldiği gibi, genç ve anlatısı kuvvetli bir kitap. Başarılarının devamını diliyorum.", source: "TRENDYOL" },
        { text: "Muazzam bir kitap. Bu kalemden çıkacak yeni eserleri merakla bekliyorum.", source: "TRENDYOL" },
        { text: "İlk başta eğreti gibi gelen gizemli şiirlerin arasına serpiştirilmiş, hayrete düşüren güzellikte şiirler. İlerledikçe kilim gibi dokunmuş sayfalar. Filozof olsan yadırgamazdım. Mükemmel.", source: "REDDIT · R/KİTAP" },
      ],
    },
    author: {
      kicker: "YAZAR — BİYOGRAFİ",
      title: "BERKAY\nDOĞAN",
      aboutKicker: "HAKKINDA",
      bio: [
        "Berkay Doğan, İstanbul'da yaşayan şair ve yazardır. Onun için yazmak bir tercih değil, bir zorunluluktur: Yazmak, varoluşun en sessiz itirafıdır. Yazmadığı her gün, kendine ihanet ettiği bir gündür.",
        "Yazıya 2017'de, on yedi yaşında başladı. O yaş, çoğu için masumiyetin sürdüğü bir eşikti; onun içinse toplumun gerçek yüzünü görmeye başladığı an oldu. O günden bu yana onu besleyen şey, edebiyatın kendisinden çok hayatın kendisidir: bir çift göz, delik deşik mimari bir yapı, eskiden geçtiği sokakları değişmiş bir adam olarak yeniden geçmek.",
        "İlk kitabı Mürekkep ve Köz: Bir Şairin Hesabı (2025) boğucu bir yalnızlığın, ulusal kaosun ve varoluşsal krizin içinden sökülerek yazıldı. İkinci kitabı Tasfiye ise mevcut düzene bir eleştiri, kaybettiğimiz felsefi dozun yeniden hayata çağrılmasıdır. İkisi arasında, şiirden denemeye uzanan bir hesaplaşma vardır.",
      ],
      worksKicker: "ESERLER",
      works: [
        { yil: "2025", eser: "Mürekkep ve Köz: Bir Şairin Hesabı", tur: "ŞİİR", yayin: "İskenderiye Yayınları" },
        { yil: "2026", eser: "Tasfiye", tur: "DENEME", yayin: "Yakında" },
      ],
    },
    contact: {
      kicker: "İLETİŞİM",
      title: ["YAZI,", "GERÇEKTEN"],
      desc: "Havadan sudan konuşmak için değil, gerçekten kanayan bir yaran varsa yaz.",
      emailLabel: "E-POSTA",
      instaLabel: "INSTAGRAM",
    },
    basinda: {
      kicker: "BASINDA",
      title: "BASINDA",
      desc: "Yayınlar, yankılar ve kilometre taşları.",
      pubKicker: "DİJİTAL VE BASILI YAYINLAR",
      publications: [
        { outlet: "Valsanat Dergisi", work: "Ruh-u Katliam", detail: "Sayı 51", linkLabel: "Dijital Arşive Git", url: "https://online.fliphtml5.com/jqzww/ezec/#p=1" },
      ],
      echoKicker: "TOPLUMSAL YANKILAR",
      echo: "Sözler hem bir isyanın hem de bir teslimiyetin izlerini taşır. Sahte yaşanmışlıklara veda eden birinin gürültüsüz ama yenilmez sessizliği.",
      echoSource: "1000Kitap",
      milestonesKicker: "KİLOMETRE TAŞLARI",
      milestones: [
        { value: "#1", label: "Trendyol Şiir Kategorisi", detail: "Mürekkep ve Köz — İskenderiye Kitap", url: "" },
        { value: "#18", label: "Trendyol Şiir — En Çok Satan", detail: "Mürekkep ve Köz — güncel sıralama", url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167" },
        { value: "#8", label: "Trendyol Şiir — En Çok Ziyaret", detail: "Mürekkep ve Köz — güncel sıralama", url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167" },
        { value: "10/10", label: "1000Kitap Okur Puanı", detail: "Mürekkep ve Köz — 300+ görüntülenme", url: "" },
        { value: "Tescil", label: "Goodreads Küresel Yazar Dizini", detail: "Mürekkep ve Köz", url: "https://www.goodreads.com/book/show/252900764-m-rekkep-ve-k-z" },
      ],
    },
    anlar: {
      kicker: "ANLAR",
      title: "ANLAR",
      desc: "İstanbul'dan kareler. Kelimelerin arasındaki sessizlikler.",
      items: [
        { src: "/images/ayna.jpg", caption: "Aynadaki yabancı" },
        { src: "/images/kedi.jpg", caption: "Şehrin sessiz tanığı" },
        { src: "/images/kitap.jpg", caption: "Açık kalmış bir sayfa" },
        { src: "/images/piyano.jpg", caption: "Susmuş bir melodi" },
        { src: "/images/bulutlar.jpg", caption: "İstanbul'un üstünde" },
      ],
      soonKicker: "YAKINDA",
      soonText: "İmza günü kareleri yakında burada.",
    },
    media: {
      kicker: "MEDYA",
      title: "ŞAİRİN\nHESABI",
      desc: "Şiir, edebiyat ve düşünceler üzerine konuşmalar. Podcast ve video.",
      podcastKicker: "DİNLE — PODCAST",
      podcastDesc: "Şairin Hesabı, tüm platformlarda. Spotify'da doğrudan dinleyebilirsin.",
      spotifyShowId: "033qeXeBwqI0ZArYivqfaL",
      spotifyEpisodes: ["300KHr8v7m33NSdFjmuhkr", "4YA4VwZqZ4UgLjBdq9gIBG"],
      videoKicker: "İZLE — YOUTUBE",
      videoDesc: "Yazar Berkay Doğan kanalında yeni videolar.",
      youtubeId: "SV7C6fD8gh8",
      links: [
        { name: "Spotify", url: "https://open.spotify.com/show/033qeXeBwqI0ZArYivqfaL" },
        { name: "Apple Podcasts", url: "https://podcasts.apple.com/tr/podcast/%C5%9Fairin-hesab%C4%B1/id1896853607?l=tr" },
        { name: "YouTube", url: "https://www.youtube.com/@yazarberkaydogan" },
      ],
    },
    newsletter: {
      kicker: "OKUR LİSTESİ",
      title: "Bir köz de sana düşsün",
      desc: "Yeni yazılar, kitaplar ve dağınık düşünceler. Ara sıra, gürültüsüz. Posta kutuna düşsün.",
      placeholder: "e-posta adresin",
      button: "KATIL",
      note: "Spam yok. İstediğin an ayrılırsın.",
      action: "https://doberkay.substack.com/subscribe",
    },
    footer: {
      sign: "Bütün yalanlar düzenin, kelimeler Berkay Doğan'ındır.",
    },
  },
  en: {
    nav: {
      home: "HOME",
      kitaplar: "BOOKS",
      tasfiye: "TASFİYE",
      murekkep: "INK AND EMBER",
      yazilar: "WRITINGS",
      medya: "MEDIA",
      anlar: "MOMENTS",
      basinda: "PRESS",
      author: "AUTHOR",
      contact: "CONTACT",
      buy: "BUY",
    },
    home: {
      kicker: "BERKAYDOGAN.CO — 2026",
      heroSub: ["To destroy is the only way to build.", "Welcome to a 161-page", "execution of existence."],
      ctaBook: "VIEW THE BOOK →",
      ctaAuthor: "AUTHOR →",
      heroPanelTop: "ESSAY COLLECTION",
      heroPanelBottom: "AUGUST 2026",
      manifestoKicker: "MANIFESTO — 2026",
      manifestoQuote: "\"Truth is the bone that remains once the fat is stripped away.\"",
      manifestoAuthor: "— BERKAY DOĞAN, TASFİYE MANIFESTO",
      books: {
        tasfiyeKicker: "AUGUST 2026 — ESSAY",
        tasfiyeTitle: "TASFİYE",
        tasfiyeDesc: "Tasfiye is a name given to everything we choose not to see.",
        tasfiyeLink: "MORE →",
        murekkepKicker: "DECEMBER 2025 — POETRY",
        murekkepTitle: "INK AND\nEMBER",
        murekkepDesc: "A Poet's Reckoning. İskenderiye Publishing. #1 in Poetry on Trendyol.",
        murekkepLink: "MORE →",
      },
      bioKicker: "AUTHOR",
      bioText: "Berkay Doğan is a poet and writer based in Istanbul. For him, writing is not a choice but a necessity: to write is the quietest confession of existence.",
      bioLink: "BIOGRAPHY →",
      heroKickerBrut: "THE SECOND BOOK — SOON",
      heroQuoteBrut: "A name given to everything we choose not to see.",
      heroCountdownLabels: ["DAYS", "HRS", "MIN"],
      heroDate: "25 AUGUST 2026",
      heroBoxMeta: "Essay · İskenderiye Publishing · August 2026",
      heroBoxLabel: "COVER SOON",
      book: {
        eyebrow: "FIRST BOOK · İSKENDERİYE · DECEMBER 2025",
        title: "Ink and Ember",
        subtitle: "A Poet's Reckoning",
        desc: "Verses torn from within a suffocating solitude, national chaos and existential crises between 2017–2022. More than 200 poems.",
        rating: "Poetry on Trendyol · #1 Most Visited",
        price: "269 ₺",
        priceTag: "ON TRENDYOL",
        buyBtn: "Buy the Book",
        readBtn: "Read an Excerpt",
        badge: "#1 POETRY ON TRENDYOL",
        hint: "Click the cover — flip it over",
        hintFlipped: "Back to the front",
      },
      backCover: {
        kicker: "BACK COVER",
        lead: "This book is not the voice of words, but of a soul that chose to be reborn from its own ashes.",
        paragraphs: [
          "The voice of one who knows no borders, who broke the chains of the mind, who defied freedom with their own body… Here, pain is not a burden; it is a door opening onto the truth.",
          "These verses are the inner reckoning of a soul at peace with its solitude, one that buried its childhood in the earth and was shaped under the weight of loving and being loved. The words carry the traces of both a revolt and a surrender.",
          "And in the end: what remains is the quiet but unbeaten silence of someone who has said farewell to lies, to false memories, to chains. This book is the echo of that silence.",
        ],
        finalA: "I am only myself now.",
        finalB: "And I was reborn; now it is your turn.",
      },
      counter: [
        { pre: "This month", num: "312", post: "readers viewed this page" },
        { pre: "", num: "146", post: "readers on the list" },
        { pre: "", num: "#1", post: "Poetry on Trendyol · Most Visited" },
      ],
      statsKicker: "NUMBERS",
      stats: [
        { num: "200+", label: "POEMS" },
        { num: "#1", label: "POETRY ON TRENDYOL" },
        { num: "5/5", label: "READER RATING" },
        { num: "8", label: "RETAILERS" },
      ],
      pressKicker: "PRESS",
      press: [
        {
          outlet: "Valsanat Literary Magazine",
          detail: "Issue 51 · February 2026",
          text: "The poem Ruh-u Katliam was published.",
          url: "https://online.fliphtml5.com/jqzww/ezec/#p=1",
        },
        {
          outlet: "Trendyol",
          detail: "Poetry Category",
          text: "#1 Most Visited.",
          url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167",
        },
        {
          outlet: "Reddit · r/Kitap",
          detail: "Reader review",
          text: "\"Poems of astonishing beauty scattered among the mysterious ones that at first felt out of place.\"",
          url: "",
        },
      ],
      colophonKicker: "COLOPHON",
      colophon: [
        { label: "PUBLISHER", value: "İskenderiye" },
        { label: "EDITION NO", value: "212" },
        { label: "GENRE", value: "Poetry" },
        { label: "PUBLISHED", value: "December 2025" },
        { label: "ISBN", value: "978-625-9620-32-9" },
        { label: "PAGES", value: "200+ poems" },
        { label: "LANGUAGE", value: "Turkish" },
        { label: "AUTHOR", value: "Berkay Doğan" },
      ],
      buyGridKicker: "WHERE TO BUY",
      buyGridNote: "Poetry #1",
      ilkKitap: "[ 01 ] FIRST BOOK",
      buyLabel: "BUY →",
      statValue: "#1",
      statLabel: "POETRY ON TRENDYOL\nBEST SELLING",
      manifestoLead: "Writing is not a choice.",
      manifestoHl: "Writing is the quietest confession of existence.",
      manifestoSig: "— BERKAY DOĞAN, SINCE 2017",
      recentKicker: "RECENT WRITINGS",
      recent: [
        { title: "A Writer's Reckoning", meta: "TASFİYE / 2026", slug: "a-writers-reckoning" },
        { title: "Dark Oxygen", meta: "TASFİYE / 2026", slug: "dark-oxygen" },
        { title: "I Am Not a God", meta: "INK AND EMBER", slug: "i-am-not-a-god" },
      ],
    },
    tasfiye: {
      kicker: "BERKAY DOĞAN — ESSAY — AUGUST 2026",
      badge: "COMING SOON — AUGUST 2026",
      notifyBtn: "NOTIFY ME WHEN IT'S OUT →",
      notifyUrl: "https://doberkay.substack.com/subscribe",
      launchKicker: "COUNTDOWN TO LAUNCH",
      countdownLabels: ["DAYS", "HRS", "MIN", "SEC"],
      launchNote: "Be the first to know when it's out — one quiet email, nothing else.",
      excerptKicker: "AN EXCERPT FROM THE BOOK",
      excerptText: "To think that what we draw into ourselves with every breath is merely nitrogen, oxygen, and the promise of a clean life is the most tragic and most innocent delusion of our age.",
      excerptLinkLabel: "Read the full excerpt →",
      excerptSlug: "dark-oxygen",
      title: "TASFİYE",
      heroDesc: "Tasfiye is a name given to everything we choose not to see.",
      meta: [
        { label: "YEAR", value: "2026" },
        { label: "GENRE", value: "ESSAY" },
        { label: "PAGES", value: "161" },
        { label: "STATUS", value: "APPROACHING" },
      ],
      aboutKicker: "ABOUT THE BOOK",
      aboutText: "Tasfiye is a name given to everything we choose not to see. An essay collection. August 2026.",
      contentsKicker: "CONTENTS",
      bolumler: [
        { no: "I", baslik: "The Wreckage of the Modern World", alt: "Social Critique", count: "16 TEXTS" },
        { no: "II", baslik: "The Social Clinic", alt: "The Exposure of Man", count: "2 TEXTS" },
        { no: "III", baslik: "The Great Purge", alt: "Purification", count: "8 TEXTS" },
      ],
      ctaKicker: "RELEASE DATE: AUGUST 2026",
      ctaTitle: "The curtain rises.",
    },
    murekkep: {
      kicker: "BERKAY DOĞAN — POETRY — DECEMBER 2025",
      title: "INK AND EMBER",
      subtitle: "A Poet's Reckoning",
      heroDesc: "Verses torn out from within a suffocating solitude, national chaos, and existential crises between 2017 and 2022.",
      meta: [
        { label: "YEAR", value: "2025" },
        { label: "GENRE", value: "POETRY" },
        { label: "PUBLISHER", value: "İSKENDERİYE" },
        { label: "TRENDYOL", value: "#1" },
      ],
      aboutKicker: "ABOUT THE BOOK",
      aboutText: "Six months after its release, it surpassed the giants of literature to claim the #1 spot in the \"Most Visited\" Poetry category on Turkey's largest marketplace. This is the absolute triumph of independent, raw craft.",
      buyKicker: "WHERE TO BUY",
      buyLinks: [
        { name: "Trendyol", url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167" },
        { name: "İskenderiye Kitap", url: "https://www.iskenderiyekitap.com/urun/murekkep-ve-koz-bir-sairin-hesabi-berkay-dogan-9786259620329" },
        { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/murekkep-ve-koz/740626.html" },
        { name: "D&R", url: "https://www.dr.com.tr/kitap/murekkep-ve-koz-bir-sairin-hesabi/berkay-dogan/edebiyat/siir/turk-siiri/urunno=0002206580001" },
        { name: "Hepsiburada", url: "https://www.hepsiburada.com/murekkep-ve-koz-pm-HBC0000BKT7HI" },
        { name: "BKM Kitap", url: "https://www.bkmkitap.com/murekkep-ve-koz" },
        { name: "İstanbul Kitapçısı", url: "https://www.istanbulkitapcisi.com/murekkep-ve-koz" },
        { name: "Maltepe Kitabevi", url: "https://www.maltepekitabevi.com/murekkep-ve-koz" },
      ],
      poemsKicker: "FROM THE BOOK",
      poemsIntro: "A few lines from Ink and Ember.",
      poems: [
        {
          title: "Grey Lives",
          lines: [
            "I am sorry for those who have lost their minds; in this world, failing to think enough leads to a great deal of foolishness. As people lose their colorful lives, they surrender to their grey ones.",
            "I am disgusted by those who say this is simply our nature, by those who believe that change will bring chaos.",
            "I wish you would drown in your grey lives without dragging our color down with you.",
            "While I curse your grey lives, while I cannot bear your turning this world's color to grey, I return once more into myself.",
          ],
        },
        {
          title: "In Love With My Future",
          lines: [
            "I am in the place no good memory can find me.",
            "I pass, treading over the narrow corners of my soul.",
            "I do not look back; I am in love with my future.",
            "I bade farewell to my false histories.",
            "I struck the waves of the seas.",
            "I could not be torn down; I tore down.",
            "My heart carried on without breaking even a sliver.",
          ],
        },
        {
          title: "I Am Not a God",
          lines: [
            "Sometimes you want to love,",
            "you want life to bind you to it.",
            "In the pit of despair you choose a poisoned heart.",
            "Perhaps your heart, once like a romantic rose,",
            "meets the curse of Medusa.",
            "I did not become this way without reason.",
            "I, too, used to love once.",
            "But I no longer want to.",
            "I am not a god.",
            "I cannot love everyone.",
            "I cannot love anyone.",
          ],
        },
      ],
      reviewKicker: "FROM READERS",
      reviews: [
        { text: "A wonderful book, very different from any poetry I've read before. I recommend it to anyone who wants to read.", source: "TRENDYOL" },
        { text: "Unexpectedly sharp and surprisingly beautiful for a young poet. Proof of how a young soul passes through the chain of moods in our country.", source: "TRENDYOL" },
        { text: "A poetic journey where words slowly seep inward like embers. Plain yet powerful. I hadn't read poems this moving in a long time.", source: "TRENDYOL" },
        { text: "Such a performance from a poet this young is remarkable. Wonderful verses, a must-read.", source: "TRENDYOL" },
        { text: "Heartfelt, young, and strong in its narrative. I wish you continued success.", source: "TRENDYOL" },
        { text: "A magnificent book. I eagerly await the new works to come from this pen.", source: "TRENDYOL" },
        { text: "Poems of astonishing beauty scattered among the mysterious ones that first seemed odd. As you go on, the pages are woven like a kilim. I wouldn't be surprised if you were a philosopher. Magnificent.", source: "REDDIT · R/KİTAP" },
      ],
    },
    author: {
      kicker: "AUTHOR — BIOGRAPHY",
      title: "BERKAY\nDOĞAN",
      aboutKicker: "ABOUT",
      bio: [
        "Berkay Doğan is a poet and writer based in Istanbul. For him, writing is not a choice but a necessity: to write is the quietest confession of existence. Every day he does not write is a day he betrays himself.",
        "He began writing in 2017, at the age of seventeen. For most, that age is a threshold where innocence lingers; for him, it was the moment he began to see the true face of society. Since then, what feeds him is not literature so much as life itself: a pair of eyes, a structure of riddled architecture, walking once-familiar streets again as a changed man.",
        "His first book, Ink and Ember: A Poet's Reckoning (2025), was torn out from within a suffocating solitude, national chaos, and existential crisis. His second book, Tasfiye, is a critique of the prevailing order, a summoning back of the philosophical measure we have lost. Between the two lies a reckoning that runs from poetry to the essay.",
      ],
      worksKicker: "WORKS",
      works: [
        { yil: "2025", eser: "Ink and Ember: A Poet's Reckoning", tur: "POETRY", yayin: "İskenderiye Publishing" },
        { yil: "2026", eser: "Tasfiye", tur: "ESSAY", yayin: "Forthcoming" },
      ],
    },
    contact: {
      kicker: "CONTACT",
      title: ["WRITE,", "FOR REAL"],
      desc: "Not to make small talk, but if you have a wound that truly bleeds, write.",
      emailLabel: "EMAIL",
      instaLabel: "INSTAGRAM",
    },
    basinda: {
      kicker: "PRESS",
      title: "PRESS",
      desc: "Publications, echoes, and milestones.",
      pubKicker: "DIGITAL AND PRINT PUBLICATIONS",
      publications: [
        { outlet: "Valsanat Magazine", work: "Ruh-u Katliam", detail: "Issue 51", linkLabel: "Go to Digital Archive", url: "https://online.fliphtml5.com/jqzww/ezec/#p=1" },
      ],
      echoKicker: "PUBLIC ECHOES",
      echo: "The words carry the traces of both a rebellion and a surrender. The noiseless yet unconquerable silence of one who has bid farewell to false histories.",
      echoSource: "1000Kitap",
      milestonesKicker: "MILESTONES",
      milestones: [
        { value: "#1", label: "Poetry Category on Trendyol", detail: "Ink and Ember — İskenderiye Kitap", url: "" },
        { value: "#18", label: "Trendyol Poetry — Best Selling", detail: "Ink and Ember — current ranking", url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167" },
        { value: "#8", label: "Trendyol Poetry — Most Visited", detail: "Ink and Ember — current ranking", url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167" },
        { value: "10/10", label: "1000Kitap Reader Rating", detail: "Ink and Ember — 300+ views", url: "" },
        { value: "Listed", label: "Goodreads Global Author Index", detail: "Ink and Ember", url: "https://www.goodreads.com/book/show/252900764-m-rekkep-ve-k-z" },
      ],
    },
    anlar: {
      kicker: "MOMENTS",
      title: "MOMENTS",
      desc: "Frames from Istanbul. The silences between the words.",
      items: [
        { src: "/images/ayna.jpg", caption: "The stranger in the mirror" },
        { src: "/images/kedi.jpg", caption: "The city's silent witness" },
        { src: "/images/kitap.jpg", caption: "A page left open" },
        { src: "/images/piyano.jpg", caption: "A silenced melody" },
        { src: "/images/bulutlar.jpg", caption: "Above Istanbul" },
      ],
      soonKicker: "COMING SOON",
      soonText: "Signature-day frames will appear here soon.",
    },
    media: {
      kicker: "MEDIA",
      title: "ŞAİRİN\nHESABI",
      desc: "Conversations on poetry, literature, and ideas. Podcast and video.",
      podcastKicker: "LISTEN — PODCAST",
      podcastDesc: "Şairin Hesabı, on every platform. Listen directly on Spotify.",
      spotifyShowId: "033qeXeBwqI0ZArYivqfaL",
      spotifyEpisodes: ["300KHr8v7m33NSdFjmuhkr", "4YA4VwZqZ4UgLjBdq9gIBG"],
      videoKicker: "WATCH — YOUTUBE",
      videoDesc: "New videos on the Yazar Berkay Doğan channel.",
      youtubeId: "SV7C6fD8gh8",
      links: [
        { name: "Spotify", url: "https://open.spotify.com/show/033qeXeBwqI0ZArYivqfaL" },
        { name: "Apple Podcasts", url: "https://podcasts.apple.com/tr/podcast/%C5%9Fairin-hesab%C4%B1/id1896853607?l=tr" },
        { name: "YouTube", url: "https://www.youtube.com/@yazarberkaydogan" },
      ],
    },
    newsletter: {
      kicker: "READER LIST",
      title: "Let an ember reach you too",
      desc: "New writings, books, and scattered thoughts. Now and then, without noise. Straight to your inbox.",
      placeholder: "your email address",
      button: "JOIN",
      note: "No spam. Leave whenever you like.",
      action: "https://doberkay.substack.com/subscribe",
    },
    footer: {
      sign: "All lies belong to the order, the words belong to Berkay Doğan.",
    },
  },
} as const;

export function getContent(lang: Lang) {
  return content[lang];
}
