export type Lang = "tr" | "en";

export const content = {
  tr: {
    nav: {
      home: "ANASAYFA",
      tasfiye: "TASFİYE",
      murekkep: "MÜREKKEP VE KÖZ",
      yazilar: "YAZILAR",
      author: "YAZAR",
      contact: "İLETİŞİM",
    },
    home: {
      kicker: "BERKAYDOGAN.CO — 2026",
      heroSub: ["Yıkmak, kurmanın tek yoludur.", "161 sayfalık bir varoluş infazına", "hoş geldiniz."],
      ctaBook: "KİTABI GÖR →",
      ctaAuthor: "YAZAR →",
      heroPanelTop: "DENEME KİTABI",
      heroPanelBottom: "ARALIK 2026",
      manifestoKicker: "MANİFESTO — 2026",
      manifestoQuote: "\"Gerçek, yağlarından arındığında ortaya çıkan kemiktir.\"",
      manifestoAuthor: "— BERKAY DOĞAN, TASFİYE MANİFESTOSU",
      books: {
        tasfiyeKicker: "ARALIK 2026 — DENEME",
        tasfiyeTitle: "TASFİYE",
        tasfiyeDesc: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir.",
        tasfiyeLink: "DAHA FAZLA →",
        murekkepKicker: "ARALIK 2025 — ŞİİR",
        murekkepTitle: "MÜREKKEP\nVE KÖZ",
        murekkepDesc: "Bir Şairin Hesabı. İskenderiye Yayınları. Trendyol Şiir #1.",
        murekkepLink: "DAHA FAZLA →",
      },
      bioKicker: "YAZAR",
      bioText: "Berkay Doğan, İstanbul'da yaşayan şair ve yazardır. Onun için yazmak bir tercih değil, bir zorunluluktur: yazmak, varoluşun en sessiz itirafıdır.",
      bioLink: "BİYOGRAFİ →",
    },
    tasfiye: {
      kicker: "BERKAY DOĞAN — DENEME — ARALIK 2026",
      title: "TASFİYE",
      heroDesc: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir.",
      meta: [
        { label: "YIL", value: "2026" },
        { label: "TÜR", value: "DENEME" },
        { label: "SAYFA", value: "161" },
        { label: "DURUM", value: "YAKINLAŞIYOR" },
      ],
      aboutKicker: "KİTAP HAKKINDA",
      aboutText: "Tasfiye, görmezden gelmeyi seçtiğimiz her şeye verilmiş bir isimdir. Deneme kitabı. Aralık 2026.",
      contentsKicker: "İÇİNDEKİLER",
      bolumler: [
        { no: "I", baslik: "Modern Dünyanın Enkazı", alt: "Toplumsal Eleştiri", count: "16 METİN" },
        { no: "II", baslik: "Toplumsal Klinik", alt: "İnsanın İfşası", count: "2 METİN" },
        { no: "III", baslik: "Büyük Tasfiye", alt: "Arınma", count: "8 METİN" },
      ],
      ctaKicker: "ÇIKIŞ TARİHİ: ARALIK 2026",
      ctaTitle: "Perde açılıyor.",
    },
    murekkep: {
      kicker: "BERKAY DOĞAN — ŞİİR — ARALIK 2025",
      title: "MÜREKKEP VE KÖZ",
      subtitle: "Bir Şairin Hesabı",
      heroDesc: "2017–2022 yılları arasında, boğucu bir yalnızlığın, ulusal kaosun ve varoluşsal krizlerin içinden sökülerek yazılan dizeler.",
      meta: [
        { label: "YIL", value: "2025" },
        { label: "TÜR", value: "ŞİİR" },
        { label: "YAYINEVİ", value: "İSKENDERİYE" },
        { label: "TRENDYOL", value: "#1" },
      ],
      aboutKicker: "KİTAP HAKKINDA",
      aboutText: "Çıkışından altı ay sonra edebiyatın dev çınarlarını geride bırakarak Türkiye'nin en büyük pazar yerinde Şiir Kategorisi \"En Çok Ziyaret Edilenler\" listesinde 1. sıraya yerleşti. Bu, bağımsız ve ham emeğin mutlak zaferidir.",
      buyKicker: "NEREDEN ALINIR",
      buyLinks: [
        { name: "Trendyol", url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167" },
        { name: "İskenderiye Kitap", url: "https://www.iskenderiyekitap.com/urun/murekkep-ve-koz-bir-sairin-hesabi-berkay-dogan-9786259620329" },
        { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/murekkep-ve-koz/740626.html" },
        { name: "D&R", url: "https://www.dr.com.tr/kitap/murekkep-ve-koz-bir-sairin-hesabi/berkay-dogan/edebiyat/siir/turk-siiri/urunno=0002206580001" },
        { name: "Hepsiburada", url: "https://www.hepsiburada.com/murekkep-ve-koz-pm-HBC0000BKT7HI" },
        { name: "BKM Kitap", url: "https://www.bkmkitap.com/murekkep-ve-koz" },
        { name: "İstanbul Kitapçısı", url: "https://www.istanbulkitapcisi.com/murekkep-ve-koz" },
        { name: "Maltepe Kitabevi", url: "https://www.maltepekitabevi.com/murekkep-ve-koz" },
      ],
      poemsKicker: "KİTAPTAN",
      poemsIntro: "Mürekkep ve Köz'den birkaç dize.",
      poems: [
        {
          title: "Gri Hayatlar",
          lines: [
            "Akıllarını kaybedenler için üzgünüm, bu dünyada yeterince düşünememek, epeyce aptallığa yol açıyor. İnsanlar renkli hayatlarını kaybederken, gri hayatlarına teslim oluyorlar.",
            "Tabiatımız böyle diyen insanlardan, değişimin kaos getireceğine inanan insanlardan tiksiniyorum.",
            "Keşke siz gri hayatlarınızda boğulsanız da rengimizi kaçırmasanız.",
            "Sizin gri hayatlarınıza lanetler okurken, bu dünyanın rengini griye çevirmenize katlanamazken, yeniden kendi içime dönüyorum.",
          ],
        },
        {
          title: "Geleceğime Âşığım",
          lines: [
            "Hiçbir iyi hatıranın beni bulmadığı yerdeyim.",
            "Çiğneye çiğneye geçiyorum ruhumun daraldığı yerleri.",
            "Geri dönmüyorum, geleceğime âşığım.",
            "Yalan yaşanmışlıklarıma veda ettim.",
            "Denizlerin dalgalarına vurdum.",
            "Yıkılamadım, yıktım.",
            "Kalbim bir gıdım bile kırılmadan devam etti.",
          ],
        },
        {
          title: "Bir Tanrı Değilim",
          lines: [
            "Bazen sevmeyi istersin,",
            "Hayata seni bağlasın istersin.",
            "Umutsuzluk çukurunda zehirli bir kalbi tercih edersin.",
            "Belki bir romantik gül misali olan kalbin,",
            "Medusa'nın lanetine erer.",
            "Nedensiz olmadım böyle.",
            "Ben de severdim eskiden.",
            "Ama istemiyorum artık.",
            "Ben Tanrı değilim.",
            "Herkesi sevemem.",
            "Kimseyi sevemem.",
          ],
        },
      ],
      reviewKicker: "OKURLARDAN",
      reviews: [
        { text: "Harika bir kitap, şimdiye kadar okuduğum şiir kitaplarından çok farklı. Okumak isteyenlere tavsiye ederim.", source: "TRENDYOL" },
        { text: "Bir genç şairden beklenmedik keskinlikte ve şaşırtıcı derecede güzel. Genç bir ruhun ülkemizde nasıl ruh halleri zincirinden geçtiğinin kanıtı.", source: "TRENDYOL" },
        { text: "Kelimelerin köz gibi yavaşça içe işlediği bir şiir yolculuğu. Sade ama güçlü bir anlatım. Uzun zamandır bu kadar dokunan şiirler okumamıştım.", source: "TRENDYOL" },
        { text: "Bu kadar genç bir şairden böyle bir performans çok başarılı. Harika dizeler, muhakkak okunmalı.", source: "TRENDYOL" },
        { text: "İçinden geldiği gibi, genç ve anlatısı kuvvetli bir kitap. Başarılarının devamını diliyorum.", source: "TRENDYOL" },
        { text: "Muazzam bir kitap. Bu kalemden çıkacak yeni eserleri merakla bekliyorum.", source: "TRENDYOL" },
        { text: "İlk başta eğreti gibi gelen gizemli şiirlerin arasına serpiştirilmiş, hayrete düşüren güzellikte şiirler. İlerledikçe kilim gibi dokunmuş sayfalar. Filozof olsan yadırgamazdım. Mükemmel.", source: "REDDIT · R/KİTAP" },
      ],
    },
    author: {
      kicker: "YAZAR — BİYOGRAFİ",
      title: "BERKAY\nDOĞAN",
      aboutKicker: "HAKKINDA",
      bio: [
        "Berkay Doğan, İstanbul'da yaşayan şair ve yazardır. Onun için yazmak bir tercih değil, bir zorunluluktur: Yazmak, varoluşun en sessiz itirafıdır. Yazmadığı her gün, kendine ihanet ettiği bir gündür.",
        "Yazıya 2017'de, on yedi yaşında başladı. O yaş, çoğu için masumiyetin sürdüğü bir eşikti; onun içinse toplumun gerçek yüzünü görmeye başladığı an oldu. O günden bu yana onu besleyen şey, edebiyatın kendisinden çok hayatın kendisidir: bir çift göz, delik deşik mimari bir yapı, eskiden geçtiği sokakları değişmiş bir adam olarak yeniden geçmek.",
        "İlk kitabı Mürekkep ve Köz: Bir Şairin Hesabı (2025) boğucu bir yalnızlığın, ulusal kaosun ve varoluşsal krizin içinden sökülerek yazıldı. İkinci kitabı Tasfiye ise mevcut düzene bir eleştiri, kaybettiğimiz felsefi dozun yeniden hayata çağrılmasıdır. İkisi arasında, şiirden denemeye uzanan bir hesaplaşma vardır.",
      ],
      worksKicker: "ESERLER",
      works: [
        { yil: "2025", eser: "Mürekkep ve Köz: Bir Şairin Hesabı", tur: "ŞİİR", yayin: "İskenderiye Yayınları" },
        { yil: "2026", eser: "Tasfiye", tur: "DENEME", yayin: "Yakında" },
      ],
    },
    contact: {
      kicker: "İLETİŞİM",
      title: ["YAZI,", "GERÇEKTEN"],
      desc: "Havadan sudan konuşmak için değil, gerçekten kanayan bir yaran varsa yaz.",
      emailLabel: "E-POSTA",
      instaLabel: "INSTAGRAM",
    },
    footer: {
      sign: "Bütün yalanlar düzenin, kelimeler Berkay Doğan'ındır.",
    },
  },
  en: {
    nav: {
      home: "HOME",
      tasfiye: "TASFİYE",
      murekkep: "INK AND EMBER",
      yazilar: "WRITINGS",
      author: "AUTHOR",
      contact: "CONTACT",
    },
    home: {
      kicker: "BERKAYDOGAN.CO — 2026",
      heroSub: ["To destroy is the only way to build.", "Welcome to a 161-page", "execution of existence."],
      ctaBook: "VIEW THE BOOK →",
      ctaAuthor: "AUTHOR →",
      heroPanelTop: "ESSAY COLLECTION",
      heroPanelBottom: "DECEMBER 2026",
      manifestoKicker: "MANIFESTO — 2026",
      manifestoQuote: "\"Truth is the bone that remains once the fat is stripped away.\"",
      manifestoAuthor: "— BERKAY DOĞAN, TASFİYE MANIFESTO",
      books: {
        tasfiyeKicker: "DECEMBER 2026 — ESSAY",
        tasfiyeTitle: "TASFİYE",
        tasfiyeDesc: "Tasfiye is a name given to everything we choose not to see.",
        tasfiyeLink: "MORE →",
        murekkepKicker: "DECEMBER 2025 — POETRY",
        murekkepTitle: "INK AND\nEMBER",
        murekkepDesc: "A Poet's Reckoning. İskenderiye Publishing. #1 in Poetry on Trendyol.",
        murekkepLink: "MORE →",
      },
      bioKicker: "AUTHOR",
      bioText: "Berkay Doğan is a poet and writer based in Istanbul. For him, writing is not a choice but a necessity: to write is the quietest confession of existence.",
      bioLink: "BIOGRAPHY →",
    },
    tasfiye: {
      kicker: "BERKAY DOĞAN — ESSAY — DECEMBER 2026",
      title: "TASFİYE",
      heroDesc: "Tasfiye is a name given to everything we choose not to see.",
      meta: [
        { label: "YEAR", value: "2026" },
        { label: "GENRE", value: "ESSAY" },
        { label: "PAGES", value: "161" },
        { label: "STATUS", value: "APPROACHING" },
      ],
      aboutKicker: "ABOUT THE BOOK",
      aboutText: "Tasfiye is a name given to everything we choose not to see. An essay collection. December 2026.",
      contentsKicker: "CONTENTS",
      bolumler: [
        { no: "I", baslik: "The Wreckage of the Modern World", alt: "Social Critique", count: "16 TEXTS" },
        { no: "II", baslik: "The Social Clinic", alt: "The Exposure of Man", count: "2 TEXTS" },
        { no: "III", baslik: "The Great Purge", alt: "Purification", count: "8 TEXTS" },
      ],
      ctaKicker: "RELEASE DATE: DECEMBER 2026",
      ctaTitle: "The curtain rises.",
    },
    murekkep: {
      kicker: "BERKAY DOĞAN — POETRY — DECEMBER 2025",
      title: "INK AND EMBER",
      subtitle: "A Poet's Reckoning",
      heroDesc: "Verses torn out from within a suffocating solitude, national chaos, and existential crises between 2017 and 2022.",
      meta: [
        { label: "YEAR", value: "2025" },
        { label: "GENRE", value: "POETRY" },
        { label: "PUBLISHER", value: "İSKENDERİYE" },
        { label: "TRENDYOL", value: "#1" },
      ],
      aboutKicker: "ABOUT THE BOOK",
      aboutText: "Six months after its release, it surpassed the giants of literature to claim the #1 spot in the \"Most Visited\" Poetry category on Turkey's largest marketplace. This is the absolute triumph of independent, raw craft.",
      buyKicker: "WHERE TO BUY",
      buyLinks: [
        { name: "Trendyol", url: "https://www.trendyol.com/iskenderiye-kitap/murekkep-ve-koz-berkay-dogan-p-1072536167" },
        { name: "İskenderiye Kitap", url: "https://www.iskenderiyekitap.com/urun/murekkep-ve-koz-bir-sairin-hesabi-berkay-dogan-9786259620329" },
        { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/murekkep-ve-koz/740626.html" },
        { name: "D&R", url: "https://www.dr.com.tr/kitap/murekkep-ve-koz-bir-sairin-hesabi/berkay-dogan/edebiyat/siir/turk-siiri/urunno=0002206580001" },
        { name: "Hepsiburada", url: "https://www.hepsiburada.com/murekkep-ve-koz-pm-HBC0000BKT7HI" },
        { name: "BKM Kitap", url: "https://www.bkmkitap.com/murekkep-ve-koz" },
        { name: "İstanbul Kitapçısı", url: "https://www.istanbulkitapcisi.com/murekkep-ve-koz" },
        { name: "Maltepe Kitabevi", url: "https://www.maltepekitabevi.com/murekkep-ve-koz" },
      ],
      poemsKicker: "FROM THE BOOK",
      poemsIntro: "A few lines from Ink and Ember.",
      poems: [
        {
          title: "Grey Lives",
          lines: [
            "I am sorry for those who have lost their minds; in this world, failing to think enough leads to a great deal of foolishness. As people lose their colorful lives, they surrender to their grey ones.",
            "I am disgusted by those who say this is simply our nature, by those who believe that change will bring chaos.",
            "I wish you would drown in your grey lives without dragging our color down with you.",
            "While I curse your grey lives, while I cannot bear your turning this world's color to grey, I return once more into myself.",
          ],
        },
        {
          title: "In Love With My Future",
          lines: [
            "I am in the place no good memory can find me.",
            "I pass, treading over the narrow corners of my soul.",
            "I do not look back; I am in love with my future.",
            "I bade farewell to my false histories.",
            "I struck the waves of the seas.",
            "I could not be torn down; I tore down.",
            "My heart carried on without breaking even a sliver.",
          ],
        },
        {
          title: "I Am Not a God",
          lines: [
            "Sometimes you want to love,",
            "you want life to bind you to it.",
            "In the pit of despair you choose a poisoned heart.",
            "Perhaps your heart, once like a romantic rose,",
            "meets the curse of Medusa.",
            "I did not become this way without reason.",
            "I, too, used to love once.",
            "But I no longer want to.",
            "I am not a god.",
            "I cannot love everyone.",
            "I cannot love anyone.",
          ],
        },
      ],
      reviewKicker: "FROM READERS",
      reviews: [
        { text: "A wonderful book, very different from any poetry I've read before. I recommend it to anyone who wants to read.", source: "TRENDYOL" },
        { text: "Unexpectedly sharp and surprisingly beautiful for a young poet. Proof of how a young soul passes through the chain of moods in our country.", source: "TRENDYOL" },
        { text: "A poetic journey where words slowly seep inward like embers. Plain yet powerful. I hadn't read poems this moving in a long time.", source: "TRENDYOL" },
        { text: "Such a performance from a poet this young is remarkable. Wonderful verses, a must-read.", source: "TRENDYOL" },
        { text: "Heartfelt, young, and strong in its narrative. I wish you continued success.", source: "TRENDYOL" },
        { text: "A magnificent book. I eagerly await the new works to come from this pen.", source: "TRENDYOL" },
        { text: "Poems of astonishing beauty scattered among the mysterious ones that first seemed odd. As you go on, the pages are woven like a kilim. I wouldn't be surprised if you were a philosopher. Magnificent.", source: "REDDIT · R/KİTAP" },
      ],
    },
    author: {
      kicker: "AUTHOR — BIOGRAPHY",
      title: "BERKAY\nDOĞAN",
      aboutKicker: "ABOUT",
      bio: [
        "Berkay Doğan is a poet and writer based in Istanbul. For him, writing is not a choice but a necessity: to write is the quietest confession of existence. Every day he does not write is a day he betrays himself.",
        "He began writing in 2017, at the age of seventeen. For most, that age is a threshold where innocence lingers; for him, it was the moment he began to see the true face of society. Since then, what feeds him is not literature so much as life itself: a pair of eyes, a structure of riddled architecture, walking once-familiar streets again as a changed man.",
        "His first book, Ink and Ember: A Poet's Reckoning (2025), was torn out from within a suffocating solitude, national chaos, and existential crisis. His second book, Tasfiye, is a critique of the prevailing order, a summoning back of the philosophical measure we have lost. Between the two lies a reckoning that runs from poetry to the essay.",
      ],
      worksKicker: "WORKS",
      works: [
        { yil: "2025", eser: "Ink and Ember: A Poet's Reckoning", tur: "POETRY", yayin: "İskenderiye Publishing" },
        { yil: "2026", eser: "Tasfiye", tur: "ESSAY", yayin: "Forthcoming" },
      ],
    },
    contact: {
      kicker: "CONTACT",
      title: ["WRITE,", "FOR REAL"],
      desc: "Not to make small talk, but if you have a wound that truly bleeds, write.",
      emailLabel: "EMAIL",
      instaLabel: "INSTAGRAM",
    },
    footer: {
      sign: "All lies belong to the order, the words belong to Berkay Doğan.",
    },
  },
} as const;

export function getContent(lang: Lang) {
  return content[lang];
}
